import type { Case, Contact } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "c1",
    country: "United States",
    name: "Ambassador Jennifer Morrison",
    title: "Legal Adviser, Department of State",
    email: "j.morrison@state.gov",
    phone: "+1-202-555-0123",
    versionHistory: [
      { date: "2024-11-15", changedBy: "Admin", changes: "Updated email address" },
      { date: "2024-09-01", changedBy: "System", changes: "Initial contact created" },
    ],
  },
  {
    id: "c2",
    country: "United Kingdom",
    name: "Sir Michael Pemberton",
    title: "Foreign & Commonwealth Office Legal Advisor",
    email: "m.pemberton@fco.gov.uk",
    phone: "+44-20-7555-0456",
    versionHistory: [
      { date: "2024-10-12", changedBy: "Admin", changes: "Updated phone number" },
    ],
  },
  {
    id: "c3",
    country: "France",
    name: "Mme. Sophie Durand",
    title: "Directrice des affaires juridiques",
    email: "s.durand@diplomatie.gouv.fr",
    phone: "+33-1-55-00-1234",
    versionHistory: [
      { date: "2024-08-20", changedBy: "System", changes: "Initial contact created" },
    ],
  },
  {
    id: "c4",
    country: "Germany",
    name: "Dr. Hans Müller",
    title: "Ministerialdirigent, Auswärtiges Amt",
    email: "h.mueller@auswaertiges-amt.de",
    phone: "+49-30-5000-5678",
    versionHistory: [],
  },
  {
    id: "c5",
    country: "Japan",
    name: "Ambassador Kenji Tanaka",
    title: "Director, International Legal Affairs Bureau",
    email: "k.tanaka@mofa.go.jp",
    phone: "+81-3-5555-7890",
    versionHistory: [],
  },
  // Add 20 more sample contacts
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `c${i + 6}`,
    country: `Country ${i + 6}`,
    name: `Contact Person ${i + 6}`,
    title: `Legal Adviser`,
    email: `contact${i + 6}@example.gov`,
    phone: `+${i + 6}-555-${String(i).padStart(4, "0")}`,
    versionHistory: [],
  })),
];

export const mockCases: Case[] = [
  {
    id: "gg-2024-001",
    title: "Certain Questions Relating to the Obligation to Prosecute or Extradite (Gabon v. Equatorial Guinea)",
    shortTitle: "Gabon v. Equatorial Guinea",
    status: "Written Proceedings",
    dateFiled: "2024-03-15",
    basisOfJurisdiction: "Article 36(2) of the Statute",
    president: "Judge Joan E. Donoghue",
    principalLegalOfficer: "Philippe Gautier",
    documentCount: 47,
    nextDeadline: "2025-02-28",
    parties: [
      {
        role: "Applicant",
        country: "Gabon",
        agent: {
          name: "H.E. Mr. Jean-Pierre Mouamba",
          title: "Ambassador",
          email: "jp.mouamba@diplomatie.ga",
        },
      },
      {
        role: "Respondent",
        country: "Equatorial Guinea",
        agent: {
          name: "H.E. Ms. Maria Estefania Nguema",
          title: "Minister of Foreign Affairs",
          email: "m.nguema@exteriores.gq",
        },
      },
    ],
    documents: [
      {
        id: "d1",
        title: "Application instituting proceedings",
        ref: "2024/1",
        date: "2024-03-15",
        pages: 45,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Key Documents",
      },
      {
        id: "d2",
        title: "Application instituting proceedings (French)",
        ref: "2024/1-FR",
        date: "2024-03-22",
        pages: 47,
        language: "FR",
        translationStatus: "Received",
        isKey: true,
        category: "Key Documents",
      },
      {
        id: "d3",
        title: "Memorial of Gabon",
        ref: "2024/8",
        date: "2024-09-15",
        pages: 320,
        language: "EN",
        translationStatus: "Awaited",
        isKey: true,
        category: "Pleadings",
        annexCount: 250,
        ocrStatus: "Partial",
        singlePdfWarning: true,
      },
      {
        id: "d4",
        title: "Order - Time-limits for filing written pleadings",
        ref: "2024/2",
        date: "2024-04-10",
        pages: 3,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Key Documents",
      },
      {
        id: "d5",
        title: "Order - Time-limits for filing written pleadings (French)",
        ref: "2024/2-FR",
        date: "2024-04-10",
        pages: 3,
        language: "FR",
        translationStatus: "Received",
        isKey: true,
        category: "Key Documents",
      },
      {
        id: "d6",
        title: "Acknowledgement of Application",
        ref: "2024/1-ACK",
        date: "2024-03-16",
        pages: 2,
        language: "EN",
        translationStatus: "Translation",
        isKey: false,
        category: "Correspondence",
      },
      {
        id: "d7",
        title: "Notification to Respondent",
        ref: "2024/1-NOT",
        date: "2024-03-18",
        pages: 1,
        language: "EN",
        translationStatus: "Translation",
        isKey: false,
        category: "Correspondence",
      },
      {
        id: "d8",
        title: "Circular Letter to UN Member States",
        ref: "2024/CIR/001",
        date: "2024-03-20",
        pages: 2,
        language: "EN",
        translationStatus: "Translation",
        isKey: false,
        category: "Correspondence",
      },
      {
        id: "d9",
        title: "Circular Letter to UN Member States (French)",
        ref: "2024/CIR/001-FR",
        date: "2024-03-27",
        pages: 2,
        language: "FR",
        translationStatus: "Received",
        isKey: false,
        category: "Correspondence",
      },
      {
        id: "d10",
        title: "Press Release",
        ref: "2024/PR/001",
        date: "2024-03-15",
        pages: 3,
        language: "EN",
        translationStatus: "Translation",
        isKey: false,
        category: "All Documents",
      },
      ...Array.from({ length: 37 }, (_, i) => ({
        id: `d${i + 11}`,
        title: `Additional Document ${i + 1}`,
        ref: `2024/${i + 11}`,
        date: "2024-08-01",
        pages: Math.floor(Math.random() * 50) + 1,
        language: (i % 2 === 0 ? "EN" : "FR") as "EN" | "FR",
        translationStatus: (["Translation", "Received", "Pending", "Awaited"][i % 4]) as any,
        isKey: false,
        category: "All Documents" as any,
      })),
    ],
    checklist: [
      {
        id: "ch1",
        phase: "initiation" as const,
        title: "Register filing in case management system",
        description: "Initial registration of application",
        status: "complete" as const,
        actions: [],
        evidence: [
          { id: "ev1", type: "event" as const, title: "Case registered", href: "#", createdAt: "2024-03-16" },
        ],
      },
      {
        id: "ch2",
        phase: "initiation" as const,
        title: "Send acknowledgement to Applicant",
        description: "Formal acknowledgement letter sent",
        status: "complete" as const,
        languages: { en: "complete" as const, fr: "complete" as const },
        actions: [],
        evidence: [
          { id: "ev2", type: "document" as const, title: "ACK-001", language: "EN" as const, href: "/icj/cases/gg-2024-001/documents/d7", createdAt: "2024-03-17" },
          { id: "ev3", type: "document" as const, title: "ACK-001", language: "FR" as const, href: "/icj/cases/gg-2024-001/documents/d8", createdAt: "2024-03-18" },
        ],
      },
      {
        id: "ch3",
        phase: "initiation" as const,
        title: "Transmit application to Respondent",
        description: "Official notification sent to Respondent",
        status: "complete" as const,
        languages: { en: "complete" as const, fr: "complete" as const },
        actions: [],
        evidence: [
          { id: "ev4", type: "document" as const, title: "TRANS-001", language: "EN" as const, href: "#", createdAt: "2024-03-18" },
          { id: "ev5", type: "document" as const, title: "TRANS-001", language: "FR" as const, href: "#", createdAt: "2024-03-19" },
        ],
      },
      {
        id: "ch4",
        phase: "initiation" as const,
        title: "Circular notification to UN Member States",
        description: "Distribute to 193 states, excluding parties",
        status: "partial" as const,
        languages: { en: "complete" as const, fr: "awaiting" as const },
        actions: [
          { id: "act1", label: "Generate FR circular", kind: "generate_letter" as const, primary: true },
          { id: "act2", label: "Create distribution (FR)", kind: "create_distribution" as const },
        ],
        evidence: [
          { id: "ev6", type: "distribution" as const, title: "Circular (EN)", language: "EN" as const, href: "#", createdAt: "2024-03-20" },
        ],
      },
      {
        id: "ch5",
        phase: "initiation" as const,
        title: "Article 63 notifications (genocide convention parties)",
        description: "Notify states party to relevant conventions",
        status: "partial" as const,
        languages: { en: "complete" as const, fr: "awaiting" as const },
        actions: [
          { id: "act3", label: "Generate notification letter (FR)", kind: "generate_letter" as const, primary: true },
        ],
        evidence: [
          { id: "ev7", type: "document" as const, title: "ART63-2024-001", language: "EN" as const, href: "/icj/cases/gg-2024-001/documents/d7", createdAt: "2024-03-22" },
        ],
      },
      {
        id: "ch6",
        phase: "initiation" as const,
        title: "Notify UN Secretary-General",
        description: "Formal notification per ICJ Statute",
        status: "complete" as const,
        languages: { en: "complete" as const, fr: "complete" as const },
        actions: [],
        evidence: [
          { id: "ev8", type: "document" as const, title: "UNSG-2024-001", language: "EN" as const, href: "#", createdAt: "2024-03-21" },
          { id: "ev9", type: "document" as const, title: "UNSG-2024-001", language: "FR" as const, href: "#", createdAt: "2024-03-22" },
        ],
      },
      {
        id: "ch7",
        phase: "initiation" as const,
        title: "Generate internal distribution cover pages",
        description: "Bilingual cover pages for judges",
        status: "complete" as const,
        languages: { en: "complete" as const, fr: "complete" as const },
        actions: [],
        evidence: [
          { id: "ev10", type: "document" as const, title: "Cover page", language: "EN" as const, href: "#", createdAt: "2024-03-23" },
          { id: "ev11", type: "document" as const, title: "Cover page", language: "FR" as const, href: "#", createdAt: "2024-03-23" },
        ],
      },
      {
        id: "ch8",
        phase: "initiation" as const,
        title: "Publish press release",
        description: "Public announcement of case filing",
        status: "complete" as const,
        actions: [],
        evidence: [
          { id: "ev12", type: "document" as const, title: "PR-2024-001", href: "/icj/cases/gg-2024-001/documents/d10", createdAt: "2024-03-15" },
        ],
      },
      {
        id: "ch9",
        phase: "initiation" as const,
        title: "Time-limits fixed by Order",
        description: "President issues procedural order",
        status: "pending" as const,
        actions: [
          { id: "act4", label: "Draft procedural order", kind: "file_document" as const, primary: true },
          { id: "act5", label: "Record in case diary", kind: "record_event" as const },
        ],
        evidence: [],
        dueDate: "2024-12-20",
      },
      {
        id: "ch10",
        phase: "initiation" as const,
        title: "Track delivery confirmations from all States",
        description: "Monitor and follow up on undelivered notifications",
        status: "pending" as const,
        actions: [
          { id: "act6", label: "Review delivery status", kind: "open_modal" as const, primary: true },
        ],
        evidence: [],
      },
    ],
    deadlines: [
      {
        id: "dl1",
        title: "Memorial of Gabon",
        date: "2024-09-15",
        party: "Applicant",
      },
      {
        id: "dl2",
        title: "Counter-Memorial of Equatorial Guinea",
        date: "2025-02-28",
        party: "Respondent",
      },
      {
        id: "dl3",
        title: "Reply of Gabon",
        date: "2025-07-15",
        party: "Applicant",
      },
    ],
    pvDecisions: [
      {
        id: "pv1",
        title: "Decision on case registration",
        date: "2024-03-16",
        ref: "PV.3201",
      },
      {
        id: "pv2",
        title: "Decision on procedural timeline",
        date: "2024-04-05",
        ref: "PV.3205",
      },
      {
        id: "pv3",
        title: "Decision on composition of Chamber (if applicable)",
        date: "2024-04-12",
        ref: "PV.3208",
      },
    ],
    distributions: [
      {
        id: "dist1",
        title: "Circular notification - Application filed",
        date: "2024-03-20",
        recipientCount: 191,
        exclusions: ["Gabon", "Equatorial Guinea"],
        attachments: ["Application (2024/1)", "Press Release (2024/PR/001)"],
        fileSizeWarning: false,
        recipients: [
          { id: "r1", name: "US Mission to UN", country: "United States", email: "legal@usun.state.gov", status: "Delivered", deliveredAt: "2024-03-20T10:23:00Z" },
          { id: "r2", name: "UK Mission to UN", country: "United Kingdom", email: "legal@ukmission.org", status: "Delivered", deliveredAt: "2024-03-20T10:25:00Z" },
          { id: "r3", name: "France Mission to UN", country: "France", email: "legal@franceonu.org", status: "Delivered", deliveredAt: "2024-03-20T10:27:00Z" },
          { id: "r4", name: "Germany Mission to UN", country: "Germany", email: "legal@new-york-un.diplo.de", status: "Delivered", deliveredAt: "2024-03-20T11:05:00Z" },
          { id: "r5", name: "Japan Mission to UN", country: "Japan", email: "legal@un.emb-japan.go.jp", status: "Pending" },
          ...Array.from({ length: 20 }, (_, i) => ({
            id: `r${i + 6}`,
            name: `Mission ${i + 6}`,
            country: `Country ${i + 6}`,
            email: `legal${i + 6}@example.gov`,
            status: (i % 10 === 0 ? "Failed" : "Delivered") as any,
            deliveredAt: i % 10 !== 0 ? "2024-03-20T12:00:00Z" : undefined,
          })),
        ],
      },
    ],
    incidentalProceedings: [],
    recentActivity: [
      {
        id: "act1",
        type: "document",
        title: "Memorial of Gabon filed",
        subtitle: "250 annexes, 320 pages",
        timestamp: "2024-09-15T14:30:00Z",
        icon: "FileText",
      },
      {
        id: "act2",
        type: "distribution",
        title: "Memorial distributed to Respondent",
        subtitle: "Delivered successfully",
        timestamp: "2024-09-16T09:15:00Z",
        icon: "Send",
      },
      {
        id: "act3",
        type: "letter",
        title: "Transmittal letter generated",
        subtitle: "English version",
        timestamp: "2024-09-16T09:00:00Z",
        icon: "Mail",
      },
      {
        id: "act4",
        type: "action",
        title: "Document marked as Key Document",
        subtitle: "Memorial of Gabon (2024/8)",
        timestamp: "2024-09-15T15:00:00Z",
        icon: "Star",
      },
    ],
    notifications: [
      {
        id: "notif-1",
        trackType: "ART63_CONVENTIONS",
        conventions: [
          {
            name: "Convention on the Prevention and Punishment of the Crime of Genocide",
            reference: "Application, para. 12",
          },
          {
            name: "International Convention on the Elimination of All Forms of Racial Discrimination",
            reference: "Application, para. 18",
          },
        ],
        registryRecommendation: "Send Art. 63 notifications to all States parties to both Conventions, excluding Parties to the dispute",
        courtDecision: {
          pvRef: "PV.2025/03",
          decisionSummary: "Send Art. 63 notifications to States parties",
        },
        lettersSent: [
          {
            id: "notif-letter-1",
            title: "ART63-2024-001",
            language: "EN",
            date: "2024-03-22",
            href: "/icj/cases/gg-2024-001/documents/d7",
          },
          {
            id: "notif-letter-2",
            title: "ART63-2024-001",
            language: "FR",
            date: "2024-03-23",
            href: "/icj/cases/gg-2024-001/documents/d8",
          },
        ],
        responsesReceived: [],
        outstandingActions: [
          {
            id: "notif-action-1",
            title: "Await responses from States parties (deadline 60 days from notification)",
            due: "2024-05-22",
          },
          {
            id: "notif-action-2",
            title: "Send follow-up if case proceeds to merits phase",
          },
        ],
        status: "waiting_response",
        lastUpdated: "2024-03-23T10:00:00Z",
      },
      {
        id: "notif-2",
        trackType: "INTERVENTION",
        conventions: [
          {
            name: "UN Secretary-General notification",
            reference: "ICJ Statute Art. 34(3)",
          },
        ],
        registryRecommendation: "Notify UN Secretary-General of case filing per Statute",
        courtDecision: {
          pvRef: "PV.2025/02",
          decisionSummary: "Transmit Application to UN Secretary-General",
        },
        lettersSent: [
          {
            id: "notif-letter-3",
            title: "UNSG-2024-001",
            language: "EN",
            date: "2024-03-16",
            href: "/icj/cases/gg-2024-001/documents/d9",
          },
          {
            id: "notif-letter-4",
            title: "UNSG-2024-001",
            language: "FR",
            date: "2024-03-16",
            href: "/icj/cases/gg-2024-001/documents/d10",
          },
        ],
        responsesReceived: [
          {
            id: "notif-resp-1",
            from: "UN Office of Legal Affairs",
            summary: "Acknowledgement of receipt",
            date: "2024-03-18",
            href: "/icj/cases/gg-2024-001/documents/d11",
          },
        ],
        outstandingActions: [],
        status: "complete",
        lastUpdated: "2024-03-18T14:30:00Z",
      },
    ],
    caseFolderStructure: [
      {
        id: "folder-1",
        title: "Institution of proceedings",
        documentIds: ["d1", "d6"],
      },
      {
        id: "folder-2",
        title: "Provisional measures",
        documentIds: [],
        children: [
          {
            id: "folder-2-1",
            title: "Request for provisional measures",
            documentIds: [],
          },
          {
            id: "folder-2-2",
            title: "Hearings",
            documentIds: [],
          },
          {
            id: "folder-2-3",
            title: "Order",
            documentIds: [],
          },
        ],
      },
      {
        id: "folder-3",
        title: "Preliminary objections",
        documentIds: [],
        children: [
          {
            id: "folder-3-1",
            title: "Preliminary objections of Respondent",
            documentIds: [],
          },
          {
            id: "folder-3-2",
            title: "Observations of Applicant",
            documentIds: [],
          },
          {
            id: "folder-3-3",
            title: "Hearings",
            documentIds: [],
          },
          {
            id: "folder-3-4",
            title: "Judgment",
            documentIds: [],
          },
        ],
      },
      {
        id: "folder-4",
        title: "Intervention",
        documentIds: [],
        children: [
          {
            id: "folder-4-1",
            title: "Declaration of intervention (Art. 63)",
            documentIds: ["d7", "d8"],
          },
          {
            id: "folder-4-2",
            title: "Observations of Parties (Art. 83(1))",
            documentIds: [],
          },
          {
            id: "folder-4-3",
            title: "Written observations of intervening States (Art. 84(2))",
            documentIds: [],
          },
          {
            id: "folder-4-4",
            title: "Decision",
            documentIds: [],
          },
        ],
      },
      {
        id: "folder-5",
        title: "Counter-claims",
        documentIds: [],
      },
      {
        id: "folder-6",
        title: "Written proceedings (Merits)",
        documentIds: ["d2", "d3", "d4", "d5"],
      },
      {
        id: "folder-7",
        title: "Oral proceedings",
        documentIds: [],
      },
      {
        id: "folder-8",
        title: "Other documents",
        documentIds: ["d9", "d10", "d11"],
        children: [
          {
            id: "folder-8-1",
            title: "Orders",
            documentIds: [],
          },
          {
            id: "folder-8-2",
            title: "Judgments",
            documentIds: [],
          },
          {
            id: "folder-8-3",
            title: "Correspondence",
            documentIds: ["d9", "d10", "d11"],
          },
        ],
      },
    ],
  },
  {
    id: "cn-2002-022",
    title: "Land and Maritime Boundary between Cameroon and Nigeria (Cameroon v. Nigeria: Equatorial Guinea intervening)",
    shortTitle: "Cameroon v. Nigeria",
    status: "Closed",
    dateFiled: "2002-03-29",
    basisOfJurisdiction: "Special Agreement of 15 November 2001",
    president: "Judge Gilbert Guillaume",
    principalLegalOfficer: "Philippe Gautier",
    documentCount: 342,
    parties: [
      {
        role: "Applicant",
        country: "Cameroon",
        agent: {
          name: "H.E. Mr. Maurice Kamto",
          title: "Minister of Justice",
          email: "m.kamto@justice.cm",
        },
      },
      {
        role: "Respondent",
        country: "Nigeria",
        agent: {
          name: "H.E. Chief Richard Akinjide",
          title: "Attorney-General",
          email: "r.akinjide@justice.gov.ng",
        },
      },
    ],
    documents: [
      {
        id: "cn-d1",
        title: "Memorial of Cameroon",
        ref: "2002/15",
        date: "2002-10-01",
        pages: 458,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Pleadings",
        annexCount: 180,
        ocrStatus: "Complete",
        singlePdfWarning: true,
      },
      {
        id: "cn-d2",
        title: "Counter-Memorial of Nigeria",
        ref: "2003/8",
        date: "2003-05-15",
        pages: 512,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Pleadings",
        annexCount: 220,
        ocrStatus: "Complete",
      },
      {
        id: "cn-d3",
        title: "Application for Permission to Intervene by Equatorial Guinea",
        ref: "2003/INT/1",
        date: "2003-06-30",
        pages: 34,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Key Documents",
      },
      {
        id: "cn-d4",
        title: "Order on Intervention",
        ref: "2003/12",
        date: "2003-10-29",
        pages: 8,
        language: "EN",
        translationStatus: "Translation",
        isKey: true,
        category: "Key Documents",
      },
      ...Array.from({ length: 338 }, (_, i) => ({
        id: `cn-d${i + 5}`,
        title: `Document ${i + 5}`,
        ref: `2002-2010/${i + 5}`,
        date: "2002-06-01",
        pages: Math.floor(Math.random() * 100) + 1,
        language: (i % 2 === 0 ? "EN" : "FR") as "EN" | "FR",
        translationStatus: "Translation" as any,
        isKey: false,
        category: "All Documents" as any,
      })),
    ],
    checklist: [
      {
        id: "cn-ch1",
        phase: "initiation" as const,
        title: "Register filing in case management system",
        description: "Initial registration of application",
        status: "completed" as const,
        actions: [],
        evidence: [],
      },
      {
        id: "cn-ch2",
        phase: "judgment" as const,
        title: "All proceedings complete",
        description: "Judgment delivered",
        status: "completed" as const,
        actions: [],
        evidence: [],
      },
    ],
    deadlines: [],
    pvDecisions: [
      {
        id: "cn-pv1",
        title: "Decision on case registration",
        date: "2002-03-30",
        ref: "PV.2801",
      },
      {
        id: "cn-pv2",
        title: "Decision on intervention application",
        date: "2003-10-20",
        ref: "PV.2845",
      },
    ],
    distributions: [],
    incidentalProceedings: [
      {
        type: "Intervention",
        status: "Granted",
        filedDate: "2003-06-30",
        documents: [
          {
            id: "cn-ip1",
            title: "Application for Permission to Intervene",
            ref: "2003/INT/1",
            date: "2003-06-30",
            pages: 34,
            language: "EN",
            translationStatus: "Translation",
            isKey: true,
            category: "Key Documents",
          },
        ],
      },
    ],
    recentActivity: [
      {
        id: "cn-act1",
        type: "action",
        title: "Case archived",
        subtitle: "Final judgment delivered",
        timestamp: "2010-11-15T10:00:00Z",
        icon: "Archive",
      },
    ],
    notifications: [],
    caseFolderStructure: [],
  },
];

export function getCaseById(id: string): Case | undefined {
  return mockCases.find((c) => c.id === id);
}

export function getContactsPage(page: number = 0, pageSize: number = 25): { contacts: Contact[]; total: number; hasMore: boolean } {
  const start = page * pageSize;
  const end = start + pageSize;
  return {
    contacts: mockContacts.slice(start, end),
    total: 193, // Mock total
    hasMore: end < 193,
  };
}
